default:
  image: python:3.8.3

stages:
  - unit-and-integraion-testing

backend-coverage:
  stage: unit-and-integraion-testing
  only:
    refs:
      - merge_requests
      - master
  script:
    - pip install -r requirements/requirements.txt
    - python manage.py migrate
    - coverage run --source='.' manage.py test --no-input
    - coverage report -m
    - coverage xml
  artifacts:
    paths:
      - coverage.xml
    reports:
      cobertura: coverage.xml
    when: on_success
    expire_in: 1 week
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"